// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prescription.Infrastructure;

#nullable disable

namespace Prescription.Infrastructure.Migrations
{
    [DbContext(typeof(PrescriptionDbContext))]
    [Migration("20251223131507_sql-data-migrate")]
    partial class sqldatamigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prescription.Domain.Entities.Advice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_advices");

                    b.ToTable("advices", (string)null);
                });

            modelBuilder.Entity("Prescription.Domain.Entities.ChiefComplaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chief_complaints");

                    b.ToTable("chief_complaints", (string)null);
                });

            modelBuilder.Entity("Prescription.Domain.Entities.Disease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Shortcut")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("shortcut");

                    b.Property<int>("SourceId")
                        .HasColumnType("int")
                        .HasColumnName("source_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_diseases");

                    b.HasIndex("Shortcut")
                        .IsUnique()
                        .HasDatabaseName("ix_diseases_shortcut");

                    b.HasIndex("SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_diseases_source_id");

                    b.ToTable("diseases", (string)null);
                });

            modelBuilder.Entity("Prescription.Domain.Entities.DiseaseDrug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DiseaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("disease_id");

                    b.Property<string>("DosageInstructions")
                        .HasColumnType("text")
                        .HasColumnName("dosage_instructions");

                    b.Property<string>("DosageInstructionsEnglish")
                        .HasColumnType("text")
                        .HasColumnName("dosage_instructions_english");

                    b.Property<Guid>("DrugId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("drug_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_disease_drugs");

                    b.HasIndex("DrugId")
                        .HasDatabaseName("ix_disease_drugs_drug_id");

                    b.HasIndex("DiseaseId", "DrugId")
                        .HasDatabaseName("ix_disease_drugs_disease_id_drug_id");

                    b.ToTable("disease_drugs", (string)null);
                });

            modelBuilder.Entity("Prescription.Domain.Entities.Drug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BrandName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("brand_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Form")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("form");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name");

                    b.Property<string>("Strength")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strength");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_drugs");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_drugs_name");

                    b.ToTable("drugs", (string)null);
                });

            modelBuilder.Entity("Prescription.Domain.Entities.Examination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_examinations");

                    b.ToTable("examinations", (string)null);
                });

            modelBuilder.Entity("Prescription.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("abbreviation");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalRange")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("normal_range");

                    b.Property<int>("OID")
                        .HasColumnType("int")
                        .HasColumnName("oid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("Abbreviation")
                        .HasDatabaseName("ix_reports_abbreviation");

                    b.HasIndex("OID")
                        .IsUnique()
                        .HasDatabaseName("ix_reports_oid");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("Prescription.Domain.Entities.Symptom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("FollowUp")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("follow_up");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name");

                    b.Property<string>("Shortcut")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("shortcut");

                    b.Property<int>("SourceId")
                        .HasColumnType("int")
                        .HasColumnName("source_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_symptoms");

                    b.HasIndex("Shortcut")
                        .IsUnique()
                        .HasDatabaseName("ix_symptoms_shortcut");

                    b.HasIndex("SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_symptoms_source_id");

                    b.ToTable("symptoms", (string)null);
                });

            modelBuilder.Entity("Prescription.Domain.Entities.SymptomAdvice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AdviceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("advice_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SymptomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("symptom_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_symptom_advices");

                    b.HasIndex("AdviceId")
                        .HasDatabaseName("ix_symptom_advices_advice_id");

                    b.HasIndex("SymptomId", "AdviceId")
                        .HasDatabaseName("ix_symptom_advices_symptom_id_advice_id");

                    b.ToTable("symptom_advices", (string)null);
                });

            modelBuilder.Entity("Prescription.Domain.Entities.SymptomChiefComplaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ChiefComplaintId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chief_complaint_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SymptomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("symptom_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_symptom_chief_complaints");

                    b.HasIndex("ChiefComplaintId")
                        .HasDatabaseName("ix_symptom_chief_complaints_chief_complaint_id");

                    b.HasIndex("SymptomId", "ChiefComplaintId")
                        .HasDatabaseName("ix_symptom_chief_complaints_symptom_id_chief_complaint_id");

                    b.ToTable("symptom_chief_complaints", (string)null);
                });

            modelBuilder.Entity("Prescription.Domain.Entities.SymptomDrug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DosageInstructions")
                        .HasColumnType("text")
                        .HasColumnName("dosage_instructions");

                    b.Property<string>("DosageInstructionsEnglish")
                        .HasColumnType("text")
                        .HasColumnName("dosage_instructions_english");

                    b.Property<Guid>("DrugId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("drug_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SymptomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("symptom_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_symptom_drugs");

                    b.HasIndex("DrugId")
                        .HasDatabaseName("ix_symptom_drugs_drug_id");

                    b.HasIndex("SymptomId", "DrugId")
                        .HasDatabaseName("ix_symptom_drugs_symptom_id_drug_id");

                    b.ToTable("symptom_drugs", (string)null);
                });

            modelBuilder.Entity("Prescription.Domain.Entities.SymptomExamination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExaminationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("examination_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SymptomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("symptom_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_symptom_examinations");

                    b.HasIndex("ExaminationId")
                        .HasDatabaseName("ix_symptom_examinations_examination_id");

                    b.HasIndex("SymptomId", "ExaminationId")
                        .HasDatabaseName("ix_symptom_examinations_symptom_id_examination_id");

                    b.ToTable("symptom_examinations", (string)null);
                });

            modelBuilder.Entity("Prescription.Domain.Entities.SymptomInvestigation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("report_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SymptomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("symptom_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_symptom_investigations");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_symptom_investigations_report_id");

                    b.HasIndex("SymptomId", "ReportId")
                        .HasDatabaseName("ix_symptom_investigations_symptom_id_report_id");

                    b.ToTable("symptom_investigations", (string)null);
                });

            modelBuilder.Entity("Prescription.Domain.Entities.DiseaseDrug", b =>
                {
                    b.HasOne("Prescription.Domain.Entities.Disease", "Disease")
                        .WithMany("DiseaseDrugs")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_disease_drugs_diseases_disease_id");

                    b.HasOne("Prescription.Domain.Entities.Drug", "Drug")
                        .WithMany("DiseaseDrugs")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_disease_drugs_drugs_drug_id");

                    b.Navigation("Disease");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("Prescription.Domain.Entities.SymptomAdvice", b =>
                {
                    b.HasOne("Prescription.Domain.Entities.Advice", "Advice")
                        .WithMany("SymptomAdvices")
                        .HasForeignKey("AdviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symptom_advices_advices_advice_id");

                    b.HasOne("Prescription.Domain.Entities.Symptom", "Symptom")
                        .WithMany("SymptomAdvices")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symptom_advices_symptoms_symptom_id");

                    b.Navigation("Advice");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("Prescription.Domain.Entities.SymptomChiefComplaint", b =>
                {
                    b.HasOne("Prescription.Domain.Entities.ChiefComplaint", "ChiefComplaint")
                        .WithMany("SymptomChiefComplaints")
                        .HasForeignKey("ChiefComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symptom_chief_complaints_chief_complaints_chief_complaint_id");

                    b.HasOne("Prescription.Domain.Entities.Symptom", "Symptom")
                        .WithMany("SymptomChiefComplaints")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symptom_chief_complaints_symptoms_symptom_id");

                    b.Navigation("ChiefComplaint");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("Prescription.Domain.Entities.SymptomDrug", b =>
                {
                    b.HasOne("Prescription.Domain.Entities.Drug", "Drug")
                        .WithMany("SymptomDrugs")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symptom_drugs_drugs_drug_id");

                    b.HasOne("Prescription.Domain.Entities.Symptom", "Symptom")
                        .WithMany("SymptomDrugs")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symptom_drugs_symptoms_symptom_id");

                    b.Navigation("Drug");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("Prescription.Domain.Entities.SymptomExamination", b =>
                {
                    b.HasOne("Prescription.Domain.Entities.Examination", "Examination")
                        .WithMany("SymptomExaminations")
                        .HasForeignKey("ExaminationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symptom_examinations_examinations_examination_id");

                    b.HasOne("Prescription.Domain.Entities.Symptom", "Symptom")
                        .WithMany("SymptomExaminations")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symptom_examinations_symptoms_symptom_id");

                    b.Navigation("Examination");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("Prescription.Domain.Entities.SymptomInvestigation", b =>
                {
                    b.HasOne("Prescription.Domain.Entities.Report", "Report")
                        .WithMany("SymptomInvestigations")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symptom_investigations_reports_report_id");

                    b.HasOne("Prescription.Domain.Entities.Symptom", "Symptom")
                        .WithMany("SymptomInvestigations")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symptom_investigations_symptoms_symptom_id");

                    b.Navigation("Report");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("Prescription.Domain.Entities.Advice", b =>
                {
                    b.Navigation("SymptomAdvices");
                });

            modelBuilder.Entity("Prescription.Domain.Entities.ChiefComplaint", b =>
                {
                    b.Navigation("SymptomChiefComplaints");
                });

            modelBuilder.Entity("Prescription.Domain.Entities.Disease", b =>
                {
                    b.Navigation("DiseaseDrugs");
                });

            modelBuilder.Entity("Prescription.Domain.Entities.Drug", b =>
                {
                    b.Navigation("DiseaseDrugs");

                    b.Navigation("SymptomDrugs");
                });

            modelBuilder.Entity("Prescription.Domain.Entities.Examination", b =>
                {
                    b.Navigation("SymptomExaminations");
                });

            modelBuilder.Entity("Prescription.Domain.Entities.Report", b =>
                {
                    b.Navigation("SymptomInvestigations");
                });

            modelBuilder.Entity("Prescription.Domain.Entities.Symptom", b =>
                {
                    b.Navigation("SymptomAdvices");

                    b.Navigation("SymptomChiefComplaints");

                    b.Navigation("SymptomDrugs");

                    b.Navigation("SymptomExaminations");

                    b.Navigation("SymptomInvestigations");
                });
#pragma warning restore 612, 618
        }
    }
}
